Repository ColdIV/forum, pull requests merged in 2022-10, with the labels that each got.

#6 Use SQLAlchemy
  .gitignore
  README.md
  app/__init__.py
  app/database.py
  app/forum.py
  app/navigation.py
  app/permissions.py
  app/views.py
  run-server.bat
  run.py
  services/__init__.py
  services/forum_database.py
  services/gen_avas.py
  services/main_db.py
  templates/pages/admin.html
  templates/pages/admin_edit_permissions.html
  templates/pages/forum_category.html
  templates/pages/forum_create_topic_pre.html
  templates/pages/forum_delete_topic.html
  templates/pages/forum_topic.html
  templates/pages/login.html
Labels: enhancement, hacktoberfest-accepted

#15 Issue 4/gdpr
  app/database.py
  app/views.py
  static/images/default-avatar.jpg
  static/styles/fonts.scss
  static/styles/styles-min.css
  static/styles/variables.scss
  templates/modules/sidebar.html
Labels: enhancement

#19 Issue 7/session update
  app/__init__.py
  app/database.py
  app/forum.py
  app/views.py
Labels: bug, enhancement

#22 Bugfix: actually show the last instead of first posts in /forum
  app/database.py
Labels: bug

#23 updated requirements.txt
  requirements.txt
Labels: documentation

#24 Extend README
  README.md
Labels: documentation
